
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='django_cached_counts',
    version='0.1.0',
    description='Caching count() in django models',
    python_requires='==3.*,>=3.8.0',
    author='ph',
    author_email='robotnaoborot@gmail.com',
    license='MIT',
    packages=['django_cached_counts'],
    package_dir={"": "."},
    package_data={},
    install_requires=['django>=2,<4'],
)
